version: "3"
services:
 
    apimanager: 
        container_name: apimanager
        image: apimanager:2016.0.1
        depends_on:
        - datastore
        - analytics
        ports:
        - "9000:9000"
        - "9100:9100"
        env_file:
        - apimanager.env 
        networks: 
        - webnet

    datastore:
        container_name: datastore_service 
        image: apimanager:2016.0.1-addons 
        ports:
        - "6379:6379"
        env_file:
        - datastore.env
        networks:
        - webnet

    analytics:
        container_name: analytics_service
        image: apimanager:2016.0.1-addons
        ports:
        - "9200:9200"
        - "9300:9300"
        env_file:
        - analytics.env
        networks:
        - webnet

networks:
        webnet: 
